"""A written summary of the advice, generated by Gemini and grounded in the data.

The numbers upstream are the analysis. This is the paragraph a person actually
reads, and the only job it has is to explain what the projections already say.
That distinction drives every decision here:

**The model is given facts and forbidden from adding any.** The payload carries
each player's price, ownership, form, availability status, the club's own
injury note, the fixture and its difficulty rating, and this tool's projection.
The prompt permits no claim that is not in that payload. It cannot report a
press conference, a rumour, or a scoreline, because it has not been given one
and it has no way to look.

**Sources are named, not implied.** Every fact in the payload is tagged with
where it came from, and the model is required to attribute claims to those
tags. The tags are real endpoints: a reader can go and check.

**House style is enforced twice.** The prompt forbids emoji and em dashes, and
`sanitise()` strips them afterwards regardless. A prompt is a request; a filter
is a guarantee.
"""

import json
import os
import re
import time
import urllib.error
import urllib.request

MODEL = os.environ.get("GEMINI_MODEL", "gemini-flash-latest")
BASE_URL = os.environ.get(
    "GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta"
)

TIMEOUT = 60
RETRIES = 4

#: Where each block of the payload comes from, quoted back to the reader so the
#: advice can be checked rather than trusted.
SOURCES = {
    "fpl_bootstrap": "FPL API, bootstrap-static (prices, ownership, form, "
                     "minutes, expected goals and assists, availability, club news)",
    "fpl_fixtures": "FPL API, fixtures (opponent, home or away, difficulty 1-5)",
    "fpl_rules": "FPL rules: 15-player squad, 11 starters, maximum 3 per club, "
                 "100.0m budget, free transfers bank to 5, each extra transfer "
                 "costs 4 points",
    "model": "This tool's projection: per-90 rates shrunk towards a "
             "price-conditional prior, scaled by fixture difficulty, blended "
             "with the FPL published ep_next for the immediate gameweek",
}

SYSTEM = """\
You are writing a short briefing for a Fantasy Premier League manager about the
gameweek ahead.

You are given a JSON payload of facts. It is the only thing you know.

Hard rules:
- Use only facts present in the payload. Invent nothing. You have no knowledge
  of injuries, team news, press conferences, results or transfers beyond what
  the payload states.
- If something is not in the payload, say that it is not known rather than
  guessing.
- Attribute every substantive claim to one of the source tags given in the
  payload's "sources" object, written in brackets, for example [fpl_bootstrap].
- Numbers must be copied from the payload, never estimated or rounded to a
  different figure.
- Do not use emoji.
- Do not use em dashes or en dashes. Use commas, full stops, or the word "to"
  for ranges.
- British English.
- Plain prose and short paragraphs. No headings made of symbols, no tables.
- Be direct about uncertainty. This is early in the season and the payload says
  how many minutes each rate is based on. Say so where it matters.
- Do not tell the reader to gamble, and do not present projections as certainty.

Structure, about 250 to 350 words in total:
1. The headline call for this gameweek, in two or three sentences.
2. The transfer decision, and why the alternative was rejected. Quote the net
   points figures.
3. The captaincy, with the two closest candidates and their projections.
4. The wildcard, and whether the payload supports playing it now.
5. One short paragraph on what this analysis cannot see.
"""


class CoachError(RuntimeError):
    def __init__(self, message, code="coach_error", status=None):
        super().__init__(message)
        self.code = code
        self.status = status


# --------------------------------------------------------------- the payload


def _player_facts(row: dict) -> dict:
    """One squad member, trimmed to what a briefing could legitimately use."""
    return {
        "name": row["name"],
        "position": row["position"],
        "club": row["team"],
        "price_m": round(row["cost"] / 10, 1),
        "owned_by_percent": row.get("selected_by"),
        "form": row.get("form"),
        "minutes_played_this_season": row.get("minutes"),
        "starts_this_season": row.get("starts"),
        "projected_points_next_gw": row["xp_next"],
        "projected_points_horizon": row["xp_horizon"],
        "availability": row.get("availability"),
        "club_news": row.get("news") or None,
        "fixtures": [
            {"gameweek": f["gw"], "opponent": f["opponent"],
             "venue": "home" if f["home"] else "away",
             "difficulty_1_to_5": f["difficulty"]}
            for f in row.get("fixtures", [])
        ],
    }


def payload_for(report: dict) -> dict:
    """Turn the report into the flat set of facts the model may speak from."""
    eleven = report["eleven"]
    wc = report["wildcard"]
    rec = report["recommended"]

    return {
        "sources": SOURCES,
        "gameweek": report["gameweek"],
        "deadline_utc": report["deadline"],
        "planning_horizon_gameweeks": report["horizon"],
        "free_transfers_available": report["free_transfers"],
        "bank_m": round(report["bank"] / 10, 1),
        "points_cost_per_extra_transfer": 4,
        "chips_already_played": report.get("chips_used") or [],
        "current_captain": (report.get("current_captain") or {}).get("name"),
        "recommended_captain": eleven["captain"]["name"],
        "captain_changes": eleven.get("captain_changes"),
        "captain_projection_next_gw": eleven["captain"]["xp_next"],
        "vice_captain": eleven["vice_captain"]["name"],
        "vice_projection_next_gw": eleven["vice_captain"]["xp_next"],
        "recommended_transfers": rec["moves"],
        "recommended_transfer_count": rec["transfers"],
        "recommended_points_hit": rec["hit"],
        "recommended_net_gain": rec["net_gain"],
        "all_plans_considered": report["plans"],
        "starting_eleven_formation": eleven["formation"],
        "starting_eleven_projected_points": eleven["expected_points"],
        "wildcard": {
            "available": wc["available"],
            "reason": wc["reason"],
            "tool_recommends_playing_it": wc["recommend"],
            "current_squad_points_over_horizon": wc["current_score"],
            "points_after_recommended_transfers": wc["plan_score"],
            "points_on_a_wildcard": wc["wildcard_score"],
            "gain_over_best_ordinary_plan": wc["gain_over_plan"],
            "players_that_would_change": wc["transfers_needed"],
        },
        "squad": [_player_facts(r) for r in report["squad"]],
        "starting_eleven": [_player_facts(r) for r in eleven["starters"]],
        "bench_in_substitution_order": [_player_facts(r) for r in eleven["bench"]],
    }


# ------------------------------------------------------------------ the call


def _text_of(response: dict) -> str:
    """Pull the answer out, ignoring the reasoning parts newer models return."""
    for candidate in response.get("candidates", []):
        parts = candidate.get("content", {}).get("parts", []) or []
        text = "".join(
            p["text"] for p in parts if p.get("text") and not p.get("thought")
        )
        if text.strip():
            return text.strip()
    return ""


def _retry_after(raw: str) -> float:
    try:
        details = json.loads(raw)["error"].get("details", [])
    except (ValueError, KeyError, TypeError):
        return 0.0
    for d in details:
        if d.get("@type", "").endswith("RetryInfo"):
            try:
                return float(str(d.get("retryDelay", "")).rstrip("s"))
            except ValueError:
                return 0.0
    return 0.0


def ask(payload: dict, api_key: str, model: str = MODEL) -> str:
    body = json.dumps({
        "systemInstruction": {"parts": [{"text": SYSTEM}]},
        "contents": [{"role": "user", "parts": [{"text": json.dumps(payload)}]}],
        "generationConfig": {"temperature": 0.3, "maxOutputTokens": 4096},
    }).encode()

    url = f"{BASE_URL}/models/{model}:generateContent"
    last = ""

    for attempt in range(RETRIES):
        request = urllib.request.Request(url, data=body, headers={
            "Content-Type": "application/json",
            "X-goog-api-key": api_key,
        })
        try:
            with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
                parsed = json.load(response)
        except urllib.error.HTTPError as e:
            raw = e.read().decode("utf-8", "replace")
            if e.code in (429, 500, 502, 503, 504) and attempt < RETRIES - 1:
                last = f"{e.code} {raw[:200]}"
                time.sleep(max(_retry_after(raw), 2 ** attempt))
                continue
            raise CoachError(
                f"Gemini returned {e.code}: {raw[:300]}",
                "coach_upstream_error", e.code,
            ) from None
        except urllib.error.URLError as e:
            if attempt < RETRIES - 1:
                last = str(e.reason)
                time.sleep(2 ** attempt)
                continue
            raise CoachError(f"Could not reach Gemini: {e.reason}",
                             "coach_unreachable") from None

        text = _text_of(parsed)
        if text:
            return text
        last = json.dumps(parsed)[:300]

    raise CoachError(f"Gemini returned no usable text: {last}", "coach_empty")


# -------------------------------------------------------------- house style

#: Emoji and pictographic ranges, plus the variation selector that trails them.
_EMOJI = re.compile(
    "[\U0001F000-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF"
    "\U00002190-\U000021FF\U00002B00-\U00002BFF️‍]"
)


def sanitise(text: str) -> str:
    """Enforce the house style rather than trusting the prompt to have done it.

    Dashes are replaced by what they were standing in for: a comma when the
    dash is doing a parenthetical job, "to" between two numbers. Doing this
    blindly with a hyphen would produce "6.78 - 6.50", which reads as
    subtraction.
    """
    text = _EMOJI.sub("", text)
    text = re.sub(r"(\d)\s*[–—]\s*(\d)", r"\1 to \2", text)
    text = re.sub(r"\s*[–—]\s*", ", ", text)
    text = re.sub(r",\s*,", ",", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    return "\n".join(line.rstrip() for line in text.splitlines()).strip()


def check(text: str) -> list[str]:
    """Anything the filter should have caught. Empty means clean."""
    problems = []
    if _EMOJI.search(text):
        problems.append("emoji present")
    if "—" in text or "–" in text:
        problems.append("em or en dash present")
    return problems


def advise(report: dict, api_key: str | None = None, model: str = MODEL) -> dict:
    key = (api_key or os.environ.get("GEMINI_API_KEY", "")).strip()
    if not key:
        # No status: a missing key is the server being unconfigured, not the
        # caller sending something wrong, so it takes the 503 declared for the
        # code rather than a 400.
        raise CoachError(
            "GEMINI_API_KEY is not set. Export it in the shell that runs the "
            "server; do not put it in a file in this repository.",
            "coach_no_key",
        )

    payload = payload_for(report)
    text = sanitise(ask(payload, key, model))
    return {
        "text": text,
        "model": model,
        "sources": SOURCES,
        "style_problems": check(text),
    }
